name: remember_me
description:  A new Flutter application that helps Muslims to develop and nurture a relationship with Allah through reflecting on the verses of the Quran and journalling their thoughts.


version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.2.0
  meta: ^1.1.8
  rxdart: ^0.23.0
  font_awesome_flutter: ^8.4.0
  http: ^0.12.1
  sqflite: ^1.3.0
  path_provider: ^1.6.11

  auto_size_text: ^2.1.0
  email_validator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/register/
    - assets/images/login/
    - assets/images/resources/
    - assets/images/themes/


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
        - asset: assets/fonts/Muli-Medium.ttf
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 600